---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress
spec:
  interval: 5m
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      version: "3.19.0"
      interval: 10m
  values:
    controller:
      ingressClass: nginx
      config:
        use-http2: "true"
      service:
        type: NodePort
        nodePorts:
          http: 32080
          https: 32443
